const DummyData =[
    {
        dayOne:{
            times:{
                timeOne: "08:00",
                timeTwo:"12:00",
                timeThree:"16:00",
                timeFour:"20:00", 
                timeFive:"24:00"
            },
           weatherIcons:{
            Icon1:"dummyIcon1",
            Icon2:"dummyIcon2",
            Icon3:"dummyIcon3",
            Icon4:"dummyIcon4", 
            Icon5:"dummyIcon5"
           },
           temperature:{
            temp1:"12ºc",
            temp2:"11ºc",
            temp3:"22ºc",
            temp4:"22ºc",
            temp5:"25ºc"
           }, 
           humidityLevel:{
            humidity1:"80%",
            humidity2:"80%",
            humidity3:"80%",
            humidity4:"80%",
            humidity5:"80%",
           }
        },
        dayTwo:{
            times:{
                timeOne: "08:00",
                timeTwo:"12:00",
                timeThree:"16:00",
                timeFour:"20:00", 
                timeFive:"24:00"
            },
           weatherIcons:{
            Icon1:"dummyIcon1",
            Icon2:"dummyIcon2",
            Icon3:"dummyIcon3",
            Icon4:"dummyIcon4", 
            Icon5:"dummyIcon5"
           },
           temperature:{
            temp1:"12ºc",
            temp2:"11ºc",
            temp3:"22ºc",
            temp4:"22ºc",
            temp5:"25ºc"
           }, 
           humidityLevel:{
            humidity1:"80%",
            humidity2:"80%",
            humidity3:"80%",
            humidity4:"80%",
            humidity5:"80%",
           }
        },
        dayThree:{
            times:{
                timeOne: "08:00",
                timeTwo:"12:00",
                timeThree:"16:00",
                timeFour:"20:00", 
                timeFive:"24:00"
            },
           weatherIcons:{
            Icon1:"dummyIcon1",
            Icon2:"dummyIcon2",
            Icon3:"dummyIcon3",
            Icon4:"dummyIcon4", 
            Icon5:"dummyIcon5"
           },
           temperature:{
            temp1:"12ºc",
            temp2:"11ºc",
            temp3:"22ºc",
            temp4:"22ºc",
            temp5:"25ºc"
           }, 
           humidityLevel:{
            humidity1:"80%",
            humidity2:"80%",
            humidity3:"80%",
            humidity4:"80%",
            humidity5:"80%",
           }
        }, 
        dayFour:{
            times:{
                timeOne: "08:00",
                timeTwo:"12:00",
                timeThree:"16:00",
                timeFour:"20:00", 
                timeFive:"24:00"
            },
           weatherIcons:{
            Icon1:"dummyIcon1",
            Icon2:"dummyIcon2",
            Icon3:"dummyIcon3",
            Icon4:"dummyIcon4", 
            Icon5:"dummyIcon5"
           },
           temperature:{
            temp1:"12ºc",
            temp2:"11ºc",
            temp3:"22ºc",
            temp4:"22ºc",
            temp5:"25ºc"
           }, 
           humidityLevel:{
            humidity1:"80%",
            humidity2:"80%",
            humidity3:"80%",
            humidity4:"80%",
            humidity5:"80%",
           }
        }, 
        dayFive:{
            times:{
                timeOne: "08:00",
                timeTwo:"12:00",
                timeThree:"16:00",
                timeFour:"20:00", 
                timeFive:"24:00"
            },
           weatherIcons:{
            Icon1:"dummyIcon1",
            Icon2:"dummyIcon2",
            Icon3:"dummyIcon3",
            Icon4:"dummyIcon4", 
            Icon5:"dummyIcon5"
           },
           temperature:{
            temp1:"12ºc",
            temp2:"11ºc",
            temp3:"22ºc",
            temp4:"22ºc",
            temp5:"25ºc"
           }, 
           humidityLevel:{
            humidity1:"80%",
            humidity2:"80%",
            humidity3:"80%",
            humidity4:"80%",
            humidity5:"80%",
           }
        }

    },
]

export default DummyData